name: "flutter_design_system_mobile_example"
description: A showcase app for the flutter design system mobile from SBB.
version: 4.11.0+20010418 # automatically set by GH Action
publish_to: "none"

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/provider
  provider: ^6.1.5

  # https://pub.dev/packages/animations
  animations: ^2.1.0

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.1.0

  # https://pub.dev/packages/intl
  intl: ^0.20.2

  sbb_design_system_mobile:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/flutter_prunekit
  flutter_prunekit: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
