# Configuration variables in array of strings defined in your repository or organization.
config-variables:
  - APPBAKERYGITHUBAPP_APPID

# Path-specific configurations.
paths:
  # Glob pattern relative to the repository root for matching files. The path separator is always '/'.
  # This example configures any YAML file under the '.github/workflows/' directory.
  .github/workflows/**/*.{yml,yaml}: