include: package:flutter/analysis_options_user.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    public_member_api_docs: false
    always_specify_types: false
    lines_longer_than_80_chars: false
    prefer_relative_imports: true
    avoid_relative_lib_imports: true
    parameter_assignments: true
    constant_identifier_names: false
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
  exclude:
    - lib/**.g.dart