name: scripts
description: "Util scripts."
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  http: ^1.1.2
  console_bars: ^1.2.0
  dart_style: ^2.3.4
  version: ^3.0.2

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^4.0.0
