name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this bug report!**
        ### Preflight Checklist
  - type: checkboxes
    id: preflight-checklist
    attributes:
      label: Preflight Checklist
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/design_system_flutter/blob/main/CONTRIBUTING.md) for this project.
          required: true
        - label: I have searched the [issue tracker](https://github.com/SchweizerischeBundesbahnen/design_system_flutter/issues) for an issue that matches the one I want to file, without success.
          required: true
  - type: markdown
    attributes:
      value: |
        ### General Information
  - type: dropdown
    id: bug-type
    attributes:
      label: Bug type
      options:
        - "Functionality"
        - "Accessibility"
        - "Performance"
        - "Security vulnerability"
        - "Other"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Which release are you using?
      description: e.g. 2.0.0
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### Environment
  - type: input
    id: flutter-version
    attributes:
      label: Flutter SDK version
      description: e.g. '3.24.5'
    validations:
      required: false
  - type: input
    id: additional-settings
    attributes:
      label: Additional settings
      placeholder: e.g. dark theme active
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### Detailed description
  - type: textarea
    id: what-was-expected
    attributes:
      label: Expected
      description: What did you expect to happen?
      placeholder: Describe what should happen if the bug was fixed.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did actually happen?
      placeholder: In contrast to the expected behavior, describe what currently happens when the bug is present.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the issue
      value: |
        1. Step one
        2. Step two
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
