name: scripts
description: "Util scripts."
version: 0.0.1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  # https://pub.dev/packages/http
  http: ^1.4.0
  # https://pub.dev/packages/console_bars
  console_bars: ^1.2.0
  # https://pub.dev/packages/dart_style
  dart_style: ^3.1.0
  # https://pub.dev/packages/version
  version: ^3.0.2

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
