name: add_issues_to_project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APPBAKERYGITHUBAPP_APPID }}
          private-key: ${{ secrets.APPBAKERYGITHUBAPP_PRIVATEKEY }}
    
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/SchweizerischeBundesbahnen/projects/5
          github-token: ${{ steps.app-token.outputs.token }}
