name: Github Release
on:
  workflow_dispatch

jobs:
  create-tag:
    if: ${{ github.event.pull_request.label == 'release' && startsWith( github.event.pull_request.title , 'Release' ) && contains( github.event.pull_request.user.login, 'bot' ) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    outputs:
      tag_name: ${{ steps.read-changelog.outputs.version }}
    
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Changelog Reader
        id: read-changelog
        uses: mindsers/changelog-reader-action@v2.2.3

      - name: Create tag
        uses: actions4git/setup-git@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: git tag -a ${{ steps.read-changelog.outputs.version }} -m "Version Release ${{ steps.read-changelog.outputs.version }} on ${{ steps.read-changelog.outputs.date }}"
      - run: git push --follow-tags

  create-github-release:
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ needs.create-tag.outputs.tag_name }}
          
      
      - name: Create GitHub Releases based on changelog
        uses: taiki-e/create-gh-release-action@v1.8.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/tags/${{ needs.create-tag.outputs.tag_name }}
          changelog: ./CHANGELOG.md
