name: Github Release
on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && contains( github.event.pull_request.labels.*.name, 'autorelease')
    permissions:
      contents: write

    outputs:
      tag_name: ${{ steps.read-changelog.outputs.version }}
    
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Changelog Reader
        id: read-changelog
        uses: mindsers/changelog-reader-action@v2.2.3

      - name: Create tag
        uses: actions4git/setup-git@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: git tag -a ${{ steps.read-changelog.outputs.version }} -m "Version Release ${{ steps.read-changelog.outputs.version }} on ${{ steps.read-changelog.outputs.date }}"
      - run: git push --follow-tags

  create-github-release:
    runs-on: ubuntu-latest
    needs: create-tag
    steps:

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ needs.create-tag.outputs.tag_name }}
          
      - name: Create GitHub Releases based on changelog
        uses: taiki-e/create-gh-release-action@v1.8.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/tags/${{ needs.create-tag.outputs.tag_name }}
          changelog: ./CHANGELOG.md
