name: Github Release
on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && contains( github.event.pull_request.labels.*.name, 'autorelease')
    permissions:
      contents: write

    outputs:
      tag_name: ${{ steps.read-changelog.outputs.version }}
      github-app-token: ${{ steps.app-token.outputs.token }}

    steps:
      - name: Generate Token for sbb-app-bakery GH App
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APPBAKERYGITHUBAPP_APPID }}
          private-key: ${{ secrets.APPBAKERYGITHUBAPP_PRIVATEKEY }}

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Changelog Reader
        id: read-changelog
        uses: mindsers/changelog-reader-action@v2.2.3

      - name: Create tag
        uses: actions4git/setup-git@v1.0.3
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          user-name: sbb-app-bakery[bot]
          user-email: 914587+sbb-app-bakery[bot]@users.noreply.github.com
      - run: git tag -a ${{ steps.read-changelog.outputs.version }} -m "Version Release ${{ steps.read-changelog.outputs.version }} on ${{ steps.read-changelog.outputs.date }}"
      - run: git push --follow-tags

  create-github-release:
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          token: ${{ needs.create-tag.outputs.github-app-token }}
          ref: refs/tags/${{ needs.create-tag.outputs.tag_name }}
          persist-credentials: false

      - name: Create GitHub Releases based on changelog
        uses: taiki-e/create-gh-release-action@v1.8.2
        with:
          token: ${{ needs.create-tag.outputs.github-app-token }}
          ref: refs/tags/${{ needs.create-tag.outputs.tag_name }}
          changelog: ./CHANGELOG.md
