name: nightly_build

on:
  workflow_dispatch:
  schedule:
    - cron: "40 2 * * *" # 02:40 am every day

jobs:
  test:
    runs-on: macos-26

    steps:

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ~26.6

      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Flutter test
        id: test
        run: flutter test

      - name: Upload goldens if tests fail
        uses: actions/upload-artifact@v7
        if: ${{ failure() && steps.test.conclusion == 'failure' }}
        with:
          name: goldens
          path: test/failures/
          retention-days: 1


  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: [ test ]
    defaults:
      run:
        working-directory: example
    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - uses: actions/setup-java@v6
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - run: flutter pub get

      - name: Build appbundle
        run: flutter build appbundle --profile --no-pub


  integration-test-ios:
    name: Integration Tests iOS
    needs: [ test ]
    runs-on: macos-26
    defaults:
      run:
        working-directory: example
    steps:

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ~26.6

      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - name: Setup iOS Simulator
        id: setup-simulator
        uses: futureware-tech/simulator-action@v5
        with:
          model: iPhone 17

      - name: Run Integration Tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 2
          retry_wait_seconds: 60
          command: cd example && flutter test -r github --no-pub -d {{ steps.setup-simulator.outputs.udid }} integration_test/app_test.dart

      - name: Upload Integration Test Results
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: integration-test-failures
          path: example/build/
          retention-days: 1

  build-iOS:
    name: Build iOS
    needs: [ test ]
    runs-on: macos-26
    defaults:
      run:
        working-directory: example
    steps:

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ~26.6

      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - name: Build iOS package
        run: flutter build ios --simulator
