name: Design System Flutter Release.

on: 
  workflow_dispatch:
    inputs:
      semantic-versioning:
        description: Whether to increase major, minor or patch.
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  release-preparation:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.update-changelog.outputs.version }}

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Update Changelog
        id: update-changelog
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: bump
          version: ${{ inputs.semantic-versioning }}
          keep-unreleased-section: true
          tag-prefix: ''

      - name: Update Pubspec version
        uses: Dbono-dev/yaml-action@v1.0.3
        with:
          changes: |
            {
              "version": "${{ steps.update-changelog.outputs.version }}"
            }
          commentOutDevDependencies: 'false'
          
      - name: Setup git environment
        uses: actions4git/setup-git@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: git add --all
      - run: git commit --message "${{ format('Pubspec and Changelog update for version {0}', steps.update-changelog.outputs.version) }}"
      - run: git tag -a ${{ steps.update-changelog.outputs.version }} -m "Version Release ${{ steps.update-changelog.outputs.version }}"
      - run: git push --follow-tags
  
  github-release:
    runs-on: ubuntu-latest
    needs: release-preparation
    steps:
      
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ needs.release-preparation.outputs.tag_name }}
          fetch-tags: 'true'

      - name: Create GitHub Releases based on changelog
        uses: taiki-e/create-gh-release-action@v1.8.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/tags/${{ needs.release-preparation.outputs.tag_name }}
          changelog: ./CHANGELOG.md
          
  
